name: Call Reusable workflow

on:
  workflow_dispatch:

jobs:
  test_call_reusable_no_params:
     uses: testacc-art/errcheck/.github/workflows/workflow-reusable.yml@master
        
  test_call_reusable_with_params:
     uses: testacc-art/errcheck/.github/workflows/workflow-reusable.yml@master
     with:
       go-version: 1.15
